export {default as About} from './About'
export {default as Cards} from './Cards'
export {default as Download} from './Download'
export {default as Features} from './Features'
export {default as Footer} from './Footer'
export {default as Hero} from './Hero'
export {default as Navbar} from './Navbar'